---
- hosts: lb
  become: yes

  tasks:
    - name: Убедиться, что пакет nginx установлен
      apt:
        name: nginx
        state: present

    - name: Убедиться, что сервис nginx запущен
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Копирует nginx.conf на место основного конфигурационного файла nginx
      copy: 
        src: ./nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - reload-nginx

    - name: Удаляет default.conf
      file: 
        path: /etc/nginx/conf.d/default.conf
        state: absent

    - template: 
        src: "./server.conf.j2"
        dest: "/etc/nginx/conf.d/{{ item.server_name }}.conf"
      vars: 
        server_port: "{{item.server_port}}"
        server_name: "{{item.server_name}}"
        path: "{{item.path}}"
        status_code: "{{item.status_code}}"
        message: "{{item.message}}"
        path2: "{{item.path2}}"
        status_code2: "{{item.status_code2}}"
        message2: "{{item.message2}}"

      loop:
        - server_port: 7070
          server_name: jmart-ansible.kz
          path: /main
          status_code: 200
          message: Добро пожаловать на JMart!
          path2: /profile
          status_code2: 201
          message2: Это страница профиля.

        - server_port: 8080
          server_name: jusan-ansible.kz
          path: /
          status_code: 200
          message: Добро пожаловать на Jusan Bank!
          path2: /account
          status_code2: 202
          message2: Здесь ваш банковский счет!
        
        - server_port: 9090
          server_name: invest-ansible.kz
          path: /home
          status_code: 200
          message: Добро пожаловать на Jusan Invest!
          path2: /user
          status_code2: 203
          message2: Это страница с вашим брокерским счетом.
      
  handlers:
    - name: reload-nginx
      service: 
        name: nginx 
        state: reloaded
